### ISSUE TITLE
Where can I find the trained weights?

### ISSUE THREAD

**Issue by NouranHany** [RuiyangJu/Fracture_Detection_Improved_YOLOv8#2]
Hello.
Firstly, I want to express my gratitude for the remarkable research and code you've shared.

I'm reaching out because I'm currently delving into the yolov8-ResCBAM model, particularly intrigued by its outstanding mAP score as highlighted on Papers with Code. However, during my search for the trained model weights, I unfortunately couldn't locate them.

I'm keen to explore further and was wondering if the trained weights for the yolov8-ResCBAM model have been uploaded anywhere. If they haven't, I completely understand, but I'm eager to inquire if there's a possibility of obtaining them.

Your assistance in this matter would be immensely appreciated, and I genuinely believe that access to these weights would significantly benefit my research endeavors.

Thank you once again for your contributions to the community, and I look forward to any guidance or assistance you can provide.

**Comment by RuiyangJu** [comment]
Hello,
Thank you for enjoying our program.
As you mentioned, we have released the trained weights for the YOLOv8-ResCBAM model in our GitHub.
You can use gdown to download the trained YOLOv8-ResCBAM model:

```
gdown https://github.com/RuiyangJu/Fracture_Detection_Improved_YOLOv8/releases/download/YOLOv8_ResCBAM/YOLOv8_ResCBAM.pt
```
In addition, if you still need some guidance or assistance, you can send e-mail to us:  jryjry1094791442@gmail.com.
